//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotionBlocks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MotionBlocks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 74) OBJ File: &apos;gso_reflex_axis_gyro.blend&apos;
        ///# www.blender.org
        ///mtllib gso_rag_base.mtl
        ///o Cube
        ///v 1.400000 0.361250 -0.400000
        ///v 1.400000 -0.361250 -0.400000
        ///v 1.400000 0.361250 1.400000
        ///v 1.400000 -0.361250 1.400000
        ///v -0.400000 0.361250 -0.400000
        ///v -0.400000 -0.361250 -0.400000
        ///v -0.400000 0.361250 1.400000
        ///v -0.400000 -0.361250 1.400000
        ///v -0.500000 -0.361250 -0.200000
        ///v 1.500000 0.361250 -0.200000
        ///v -0.500000 0.361250 -0.200000
        ///v 1.500000 -0.361250 -0.200000
        ///v -0.500000 -0.361250 1.200000
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gso_rag_base {
            get {
                return ResourceManager.GetString("gso_rag_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 74) OBJ File: &apos;gso_reflex_axis_gyro.blend&apos;
        ///# www.blender.org
        ///mtllib gso_rag_drum.mtl
        ///o Cylinder_Cylinder.001
        ///v 0.000000 -0.350000 -0.000000
        ///v 0.000000 0.350000 -0.000000
        ///v 0.000000 -0.350000 -0.840000
        ///v 0.000000 0.350000 -0.840000
        ///v 0.420000 -0.350000 -0.727461
        ///v 0.420000 0.350000 -0.727461
        ///v 0.363731 -0.175000 -0.210000
        ///v 0.363731 0.175000 -0.210000
        ///v 0.840000 -0.350000 0.000000
        ///v 0.840000 0.350000 0.000000
        ///v 0.727461 -0.350000 0.420000
        ///v 0.727461 0.350000 0.420000
        ///v 0.420000 -0.350000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gso_rag_drum {
            get {
                return ResourceManager.GetString("gso_rag_drum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gso_reflex_axis_gyro_png {
            get {
                object obj = ResourceManager.GetObject("gso_reflex_axis_gyro_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
