//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotionBlocks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MotionBlocks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 75) OBJ File: &apos;BF_Small_Floater_Tank.blend&apos;
        ///# www.blender.org
        ///mtllib BF_Small_Floater_Tank.mtl
        ///o BF_Small_Floater_Tank
        ///v 0.319892 -0.426202 1.230100
        ///v 0.319892 -0.426202 -0.229634
        ///v 0.319892 -0.499999 -0.229634
        ///v 0.319892 -0.499999 1.230100
        ///v 0.352304 -0.421935 -0.377803
        ///v 0.319892 -0.426202 -0.377803
        ///v 0.319892 -0.426202 1.378270
        ///v 0.352304 -0.421935 1.378270
        ///v -0.319938 -0.426202 -0.377803
        ///v -0.352351 -0.421935 -0.377803
        ///v -0.381943 -0.409677 -0.377803
        ///v -0.407355 -0.390178 -0.377803
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bf_small_floater_tank {
            get {
                return ResourceManager.GetString("bf_small_floater_tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bf_small_floater_tank_png {
            get {
                object obj = ResourceManager.GetObject("bf_small_floater_tank_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 74) OBJ File: &apos;gso_ballast.blend&apos;
        ///# www.blender.org
        ///mtllib gso_ballast.mtl
        ///o Cube_Cube.000
        ///v -0.132023 -0.132023 0.500001
        ///v 0.000000 -0.000000 0.600002
        ///v -0.132023 0.132023 0.500001
        ///v 0.132023 -0.132023 0.500001
        ///v 0.132023 0.132023 0.500001
        ///v -0.132025 0.500000 -0.132020
        ///v -0.000002 0.600000 0.000004
        ///v 0.132021 0.500000 -0.132020
        ///v -0.132025 0.500000 0.132026
        ///v 0.132021 0.500000 0.132026
        ///v -0.500001 -0.132022 -0.132020
        ///v -0.600002 0.000001 0.000004
        ///v -0.500002 0.132023 -0.132020
        ///v -0.50 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gso_ballast {
            get {
                return ResourceManager.GetString("gso_ballast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gso_ballast_png {
            get {
                object obj = ResourceManager.GetObject("gso_ballast_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 74) OBJ File: &apos;gso_ballast.blend&apos;
        ///# www.blender.org
        ///mtllib gso_ballast_weight.mtl
        ///o Icosphere
        ///v -0.000000 -0.450000 0.000000
        ///v 0.424748 -0.262512 0.308594
        ///v -0.143134 -0.231603 0.440529
        ///v -0.444345 -0.222174 0.000000
        ///v -0.143134 -0.231603 -0.440529
        ///v 0.424748 -0.262512 -0.308594
        ///v 0.143134 0.231604 0.440529
        ///v -0.424748 0.262512 0.308594
        ///v -0.424748 0.262512 -0.308594
        ///v 0.143134 0.231604 -0.440529
        ///v 0.444345 0.222174 0.000000
        ///v -0.000000 0.450000 0.000000
        ///v -0.137661 -0.388772 0.423683
        ///v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gso_ballast_weight {
            get {
                return ResourceManager.GetString("gso_ballast_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 74) OBJ File: &apos;gso_reflex_axis_gyro.blend&apos;
        ///# www.blender.org
        ///mtllib gso_rag_base.mtl
        ///o Cube
        ///v 1.400000 -0.361250 -0.400000
        ///v 1.400000 -0.361250 1.400000
        ///v -0.165000 -0.361250 -0.450000
        ///v -0.400000 -0.361250 1.400000
        ///v -0.355000 -0.361250 -0.355000
        ///v 1.500000 -0.361250 -0.200000
        ///v -0.500000 -0.361250 1.200000
        ///v 1.500000 -0.361250 1.200000
        ///v 1.200000 -0.361250 -0.500000
        ///v 1.200000 -0.361250 1.500000
        ///v 1.307500 -0.500000 -0.307500
        ///v 1.307500 -0.500000 1.307500
        ///v 0.422537 0.450000 1.263463
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gso_rag_base {
            get {
                return ResourceManager.GetString("gso_rag_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 74) OBJ File: &apos;gso_reflex_axis_gyro.blend&apos;
        ///# www.blender.org
        ///mtllib gso_rag_drum.mtl
        ///o Cylinder_Cylinder.001
        ///v 0.000000 -0.350000 -0.000000
        ///v 0.000000 0.350000 -0.000000
        ///v 0.000000 -0.350000 -0.840000
        ///v 0.000000 0.350000 -0.840000
        ///v 0.420000 -0.350000 -0.727461
        ///v 0.420000 0.350000 -0.727461
        ///v 0.363731 -0.175000 -0.210000
        ///v 0.363731 0.175000 -0.210000
        ///v 0.840000 -0.350000 0.000000
        ///v 0.840000 0.350000 0.000000
        ///v 0.727461 -0.350000 0.420000
        ///v 0.727461 0.350000 0.420000
        ///v 0.420000 -0.350000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gso_rag_drum {
            get {
                return ResourceManager.GetString("gso_rag_drum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gso_reflex_axis_gyro_png {
            get {
                object obj = ResourceManager.GetObject("gso_reflex_axis_gyro_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
